### ISSUE TITLE
Sugerencia: corrección de Button Check-input

### ISSUE THREAD

**Issue by ReinaFresita** [fedegaay/mercadoLiebre#1]
https://mercado-liebre-fg.onrender.com/register

![Captura de pantalla (908)](https://user-images.githubusercontent.com/109054165/210671100-04f75613-5f50-4b27-9432-cdeff8cd0e83.png)

Sugiero cambiar el button check-input por button radius y poner checked a alguna de las opciones.

En el primer o segundo input type="radio" poner checked para que se marque automáticamente Sugiero poner en Comprador ya que la mayoría de clientes serán compradores.

`
    <input type="radio">
    <p class="type">Comprador</p>
`
`

    <input type="radio">

    <p class="type">Vendedor</p>
`

La clase "type" debe ser cambiada a la clase que poseas en tu hoja de estilos.

Saludos 🤗🤍!!

**Comment by fedegaay** [comment]
Gracias por el comentario, buen aporte, en este caso lo deje asi porque pense que estaba la posiblidad de que al momento de registrarse pueda marcar las dos opciones para tener un perfil completo. Chequeo la informacion en las actividades que nos dejaron y lo modifico. Muchas gracias por tu aporte, saludos.

**Comment by fedegaay** [comment]
Mica estuve consultado con los profesores y dando mi explicacion de porque lo hice asi y me dijeron que esta bien echo de esa manera si yo interpreto que quiero que el usuario al registrarse tenga los dos perfiles (tanto vendedor como comprador) esa fue mi manera de pensarlo y hacerlo cuando cree el registro. Saludos

**Comment by ReinaFresita** [comment]
Dale, no hay problema Fede, no había considerado esa posibilidad y me base en las imágenes de los pdfs. Doy por terminado este hilo, muy buena página, la usaré de inspiración para seguir mejorando!

Saludos 🤗🤍!!
